# first=input("enter first number:")
# second=input("enter second number:")
# sum=int(first)+int(second)
# print("the sumis:"+str(sum))
# string
name="Tony Stark"
# print(name.upper())
# print(name.lower())
# print(name)
# print(name.find('S'))
# print(name.find(' '))
# print(name.find('a'))
# print(name.find('*'))
# print(name.replace("Tony Stark","Ironman"))
# print(name)
print("Stark" in name)
